name: web_scraping_env
channels:
  - defaults
dependencies:
  - python=3.6
  - pandas
  - beautifulsoup4
  - selenium
  - chromium-chromedriver
  - pip
  - pip:
    - bs4==0.0.1
    - webdriver_manager==3.5.1
