name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  mongo_db: ${{ secrets.MONGO_DB }}
  mongo_table: ${{ secrets.MONGO_TABLE }}
  mongo_url: ${{ secrets.MONGO_URL }}
  start_year: ${{ START_YEAR }}
  start_month: ${{ START_MONTH }}
  start_day: ${{ START_DAY }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install bs4 pandas selenium pymongo
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run main Python script
      run: |
        python agmarknet_daily_v2.py
